friends_name = "    sparsh tiwari   "
print (friends_name)
print (friends_name.upper())
print (friends_name.lower())
print (friends_name.split())
print (friends_name.title())
print (friends_name.strip())
print ()
friends_name = friends_name.strip().title()
print (friends_name,end='')
print (friends_name.upper().split())
